apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  labels:
    app:  backend
spec:
  replicas: 2
  selector: 
    matchLabels:
      app:  backend
  template:
    metadata:
      labels:
        app:  backend
    spec:
      containers:
        - name: backend-container
          image: 023231074572.dkr.ecr.us-east-1.amazonaws.com/shopping-site-backend:5f9d3bae3232c4c2f50c06ec6c7e6f33f463c33d
          ports:
            - containerPort:  5000
          envFrom:
            - configMapRef:
                name: backend-config
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
          limits:
              cpu: "500m"
              memory: "512Mi"

---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec:
  selector:
    app:  backend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
  type: ClusterIP